import { describe, it, expect, expectTypeOf, beforeAll, afterAll } from 'vitest';
import { createTestContext, mockClock, must, _resetDefaultContextForTesting } from '@flyingrobots/bijou/adapters/test';
import {
  colorHex,
  createSurface,
  getDefaultContext,
  setDefaultContext,
  stringToSurface,
  surfaceToString,
  type BijouContext,
  type Surface,
} from '@flyingrobots/bijou';
import { createI18nRuntime } from '@flyingrobots/bijou-i18n';
import { createKeyMap } from './keybindings.js';
import { createSplitPaneState } from './split-pane.js';
import { mouseMove, mousePress, mouseRelease, runScript } from './driver.js';
import { normalizeViewOutput } from './view-output.js';
import { FRAME_I18N_CATALOG } from './app-frame-i18n.js';
import {
  createNotificationState,
  dismissNotification,
  hitTestNotificationStack,
  pushNotification,
  tickNotifications,
  type NotificationHistoryFilter,
  type NotificationState,
} from './notification.js';
import {
  activeFrameLayer,
  createFramedApp,
  describeFrameLayerStack,
  describeFrameRuntimeViewStack,
  notify,
  projectFrameControls,
  runFramedApp,
  type FramePage,
  type FramePageMsg,
  type FramedApp,
  type FramedAppMsg,
  type FramedAppUpdateResult,
  type FrameOverlayContext,
  type PageTransition,
  underlyingFrameLayer,
  wrapFrameMsg,
} from './app-frame.js';
import { activeRuntimeView } from './runtime-engine.js';
import { QUIT, isCmdCleanup, type Cmd, type MouseMsg } from './types.js';
import { tick } from './commands.js';
import { ENABLE_MOUSE, KEY_BACKTICK, KEY_CTRL_P, KEY_DOWN, KEY_ENTER, KEY_ESCAPE, KEY_SHIFT_TAB, KEY_TAB, collectCommandMessages, createAlternateShellTheme, createInteractiveContext, createSameNameAlternateShellTheme, ctrlKey, makeLongContent, scheduleKeys, shiftKey, textView } from './app-frame.test-support.part01.js';
import type { Msg, PageModel } from './app-frame.test-support.part01.js';
import { makeModalPage, makePage, seedNotificationHistory, surfaceHasBg, surfaceHasFg } from './app-frame.test-support.part02.js';
export {
  activeFrameLayer,
  activeRuntimeView,
  afterAll,
  beforeAll,
  collectCommandMessages,
  createAlternateShellTheme,
  createFramedApp,
  createI18nRuntime,
  createInteractiveContext,
  createKeyMap,
  createNotificationState,
  createSameNameAlternateShellTheme,
  createSplitPaneState,
  createSurface,
  createTestContext,
  ctrlKey,
  describe,
  describeFrameLayerStack,
  describeFrameRuntimeViewStack,
  dismissNotification,
  ENABLE_MOUSE,
  colorHex,
  expect,
  expectTypeOf,
  FRAME_I18N_CATALOG,
  getDefaultContext,
  hitTestNotificationStack,
  isCmdCleanup,
  it,
  KEY_BACKTICK,
  KEY_CTRL_P,
  KEY_DOWN,
  KEY_ENTER,
  KEY_ESCAPE,
  KEY_SHIFT_TAB,
  KEY_TAB,
  makeLongContent,
  makeModalPage,
  makePage,
  mockClock,
  must,
  mouseMove,
  mousePress,
  mouseRelease,
  normalizeViewOutput,
  notify,
  projectFrameControls,
  pushNotification,
  QUIT,
  runFramedApp,
  runScript,
  scheduleKeys,
  seedNotificationHistory,
  setDefaultContext,
  shiftKey,
  stringToSurface,
  surfaceHasBg,
  surfaceHasFg,
  surfaceToString,
  textView,
  tick,
  tickNotifications,
  underlyingFrameLayer,
  wrapFrameMsg,
  _resetDefaultContextForTesting,
};
export type {
  BijouContext,
  Cmd,
  FrameOverlayContext,
  FramePage,
  FramePageMsg,
  FramedApp,
  FramedAppMsg,
  FramedAppUpdateResult,
  MouseMsg,
  Msg,
  NotificationHistoryFilter,
  NotificationState,
  PageModel,
  PageTransition,
  Surface,
};
