// Constraint grid layout
export {
  type GridTrack,
  type GridOptions,
  type GridSurfaceOptions,
  type GridLayoutResult,
  gridLayout,
  grid,
  gridSurface,
} from './grid.js';

// App frame shell
export {
  type FrameCommandItem,
  type FrameInputArea,
  type FrameLayerHintSource,
  type FrameLayerKind,
  type FrameLayerMetadata,
  type FrameLayerOwner,
  type FrameLayerDescriptor,
  type FramePageLayerKind,
  type FramePageLayerRegistry,
  type FrameControlProjection,
  type FrameRuntimeLayer,
  type FrameRuntimeViewStack,
  type DescribeFrameLayerStackOptions,
  type FrameHeaderStyle,
  type FrameShellTheme,
  type FrameShellThemeFamily,
  type FrameShellThemeMode,
  type FrameShellThemeModeSupport,
  type FrameShellThemeSpec,
  type FrameShellThemeChange,
  type FramePage,
  type FramePageMsg,
  type FramePageUpdateResult,
  type FrameLayoutNode,
  type FrameOverlayContext,
  type FrameRuntimeNotificationOptions,
  type CreateFramedAppOptions,
  type PageTransition,
  type FramePaneScroll,
  type FrameModel,
  type FrameAction,
  type FrameNotificationSpec,
  type FramedApp,
  type FramedAppRunOptions,
  type FramedAppMsg,
  type FramedAppUpdateResult,
  type FrameScopedMsg,
  type PageScopedMsg,
  type FrameTimingSnapshot,
  type FramePerfHudTelemetry,
  type FramePerfHudOverlayOptions,
  activeFrameLayer,
  describeFrameLayerStack,
  describeFrameRuntimeViewStack,
  createFramedApp,
  emitMsg,
  emitFrameAction,
  emitMsgForPage,
  FRAME_MSG_TOKEN,
  isFrameScopedMsg,
  isPageScopedMsg,
  notify,
  PAGE_MSG_TOKEN,
  projectFrameControls,
  renderFramePerfHudOverlay,
  runFramedApp,
  FRAME_SHELL_THEME_MODE_SUPPORT,
  summarizeFrameTimings,
  underlyingFrameLayer,
  wrapCmdForPage,
  wrapFrameMsg,
  wrapPageMsg,
} from './app-frame.js';

// Panel state (minimize/maximize)
export {
  type PanelVisibilityState,
  type PanelMaximizeState,
  createPanelVisibilityState,
  createPanelMaximizeState,
  toggleMinimized,
  minimizePane,
  restorePane,
  isMinimized,
  toggleMaximize,
} from './panel-state.js';

// Panel dock (reorder panes)
export {
  type DockDirection,
  type PanelDockState,
  createPanelDockState,
  movePaneInContainer,
  resolveChildOrder,
  findPaneContainer,
  getNodeId,
} from './panel-dock.js';

// Layout presets + session restore
export {
  type SerializedPageLayout,
  type SerializedLayoutState,
  type LayoutPreset,
  serializeLayoutState,
  restoreLayoutState,
  presetSideBySide,
  presetStacked,
  presetFocused,
} from './layout-preset.js';
