import { defineBlockPackage, type BlockPackageManifest } from '../block-metadata.js';
import { BIJOU_PACKAGE, type StandardBlockStory } from './types.js';
import { appShellBlock, readerSurfaceBlock, inspectorPanelBlock, inlineStatusBlock, inFlowStatusBlock, transientOverlayBlock, activityStreamBlock, shortcutCueBlock, progressIndicatorBlock, framedGroupBlock, explainabilityWalkthroughBlock, formattedDocumentBlock, linkDestinationBlock, dividerBlock, textEntryBlock, singleChoiceBlock, multipleChoiceBlock, binaryDecisionBlock, peerNavigationBlock, progressiveDisclosureBlock, pathProgressBlock, brandEmphasisBlock, modeAwarePrimitiveBlock, denseComparisonBlock, hierarchyBlock, explorationListBlock, temporalDependencyBlock } from './block-definitions.js';
import { standardBlockStory } from './metadata-standard.js';

export const standardBlocks = Object.freeze([
  appShellBlock,
  readerSurfaceBlock,
  inspectorPanelBlock,
  inlineStatusBlock,
  inFlowStatusBlock,
  transientOverlayBlock,
  activityStreamBlock,
  shortcutCueBlock,
  progressIndicatorBlock,
  framedGroupBlock,
  explainabilityWalkthroughBlock,
  formattedDocumentBlock,
  linkDestinationBlock,
  dividerBlock,
  textEntryBlock,
  singleChoiceBlock,
  multipleChoiceBlock,
  binaryDecisionBlock,
  peerNavigationBlock,
  progressiveDisclosureBlock,
  pathProgressBlock,
  brandEmphasisBlock,
  modeAwarePrimitiveBlock,
  denseComparisonBlock,
  hierarchyBlock,
  explorationListBlock,
  temporalDependencyBlock,
]);

export const standardBlockStories: readonly StandardBlockStory[] = Object.freeze([
  standardBlockStory('app-shell.ready', 'AppShell', 'Ready shell', 'ready'),
  standardBlockStory('app-shell.narrow', 'AppShell', 'Narrow shell', 'narrow'),
  standardBlockStory('app-shell.overlay', 'AppShell', 'Overlay shell', 'overlay'),
  standardBlockStory('reader-surface.ready', 'ReaderSurface', 'Reader ready', 'ready'),
  standardBlockStory('reader-surface.loading', 'ReaderSurface', 'Reader loading', 'loading'),
  standardBlockStory('reader-surface.stale', 'ReaderSurface', 'Reader stale', 'stale'),
  standardBlockStory('reader-surface.empty', 'ReaderSurface', 'Reader empty', 'empty'),
  standardBlockStory('reader-surface.error', 'ReaderSurface', 'Reader error', 'error'),
  standardBlockStory('inspector-panel.ready', 'InspectorPanel', 'Inspector ready', 'ready'),
  standardBlockStory('inspector-panel.empty', 'InspectorPanel', 'Inspector empty', 'empty'),
  standardBlockStory('inspector-panel.loading', 'InspectorPanel', 'Inspector loading', 'loading'),
  standardBlockStory('inspector-panel.stale', 'InspectorPanel', 'Inspector stale', 'stale'),
  standardBlockStory('inspector-panel.error', 'InspectorPanel', 'Inspector error', 'error'),
  standardBlockStory('inline-status.ready', 'InlineStatusBlock', 'Inline status ready', 'ready'),
  standardBlockStory('in-flow-status.ready', 'InFlowStatusBlock', 'In-flow status ready', 'ready'),
  standardBlockStory('transient-overlay.ready', 'TransientOverlayBlock', 'Transient overlay ready', 'ready'),
  standardBlockStory('activity-stream.ready', 'ActivityStreamBlock', 'Activity stream ready', 'ready'),
  standardBlockStory('shortcut-cue.ready', 'ShortcutCueBlock', 'Shortcut cue ready', 'ready'),
  standardBlockStory('progress-indicator.ready', 'ProgressIndicatorBlock', 'Progress indicator ready', 'ready'),
  standardBlockStory('framed-group.ready', 'FramedGroupBlock', 'Framed group ready', 'ready'),
  standardBlockStory(
    'explainability-walkthrough.ready',
    'ExplainabilityWalkthroughBlock',
    'Explainability walkthrough ready',
    'ready',
  ),
  standardBlockStory('formatted-document.ready', 'FormattedDocumentBlock', 'Formatted document ready', 'ready'),
  standardBlockStory('link-destination.ready', 'LinkDestinationBlock', 'Link destination ready', 'ready'),
  standardBlockStory('divider.ready', 'DividerBlock', 'Divider ready', 'ready'),
  standardBlockStory('text-entry.ready', 'TextEntryBlock', 'Text entry ready', 'ready'),
  standardBlockStory('single-choice.ready', 'SingleChoiceBlock', 'Single choice ready', 'ready'),
  standardBlockStory('multiple-choice.ready', 'MultipleChoiceBlock', 'Multiple choice ready', 'ready'),
  standardBlockStory('binary-decision.ready', 'BinaryDecisionBlock', 'Binary decision ready', 'ready'),
  standardBlockStory('peer-navigation.ready', 'PeerNavigationBlock', 'Peer navigation ready', 'ready'),
  standardBlockStory(
    'progressive-disclosure.ready',
    'ProgressiveDisclosureBlock',
    'Progressive disclosure ready',
    'ready',
  ),
  standardBlockStory('path-progress.ready', 'PathProgressBlock', 'Path progress ready', 'ready'),
  standardBlockStory('brand-emphasis.ready', 'BrandEmphasisBlock', 'Brand emphasis ready', 'ready'),
  standardBlockStory(
    'mode-aware-primitive.ready',
    'ModeAwarePrimitiveBlock',
    'Mode-aware primitive ready',
    'ready',
  ),
  standardBlockStory('dense-comparison.ready', 'DenseComparisonBlock', 'Dense comparison ready', 'ready'),
  standardBlockStory('hierarchy.ready', 'HierarchyBlock', 'Hierarchy ready', 'ready'),
  standardBlockStory('exploration-list.ready', 'ExplorationListBlock', 'Exploration list ready', 'ready'),
  standardBlockStory(
    'temporal-dependency.ready',
    'TemporalDependencyBlock',
    'Temporal dependency ready',
    'ready',
  ),
]);

export const standardBlockPackageManifest: BlockPackageManifest = defineBlockPackage({
  packageName: BIJOU_PACKAGE,
  version: '5.0.0',
  bijouPeerRange: '^5.0.0',
  blocks: standardBlocks.map((block) => block.metadata.blockName),
  docs: [
    'docs/design-system/blocks.md',
    'docs/design/DX-031-standard-bijou-blocks.md',
    'docs/design/DF-039-component-family-standard-blocks.md',
    'docs/design/DF-046-choice-navigation-standard-blocks.md',
    'docs/design/DF-054-late-family-standard-blocks.md',
  ],
  tags: ['standard-blocks', 'dx-031', 'first-party'],
});
