import {
  activityStreamBlock,
  activityStreamSchemaBlock,
  bindSchemaBlockInput,
  inFlowStatusBlock,
  inFlowStatusSchemaBlock,
  inlineStatusBlock,
  inlineStatusSchemaBlock,
  progressIndicatorBlock,
  progressIndicatorSchemaBlock,
  shortcutCueBlock,
  shortcutCueSchemaBlock,
  transientOverlayBlock,
  transientOverlaySchemaBlock,
} from '../../../packages/bijou/src/index.js';

const STATUS_FEEDBACK_SCHEMA_BLOCKS = [
  {
    block: inlineStatusBlock,
    schemaBlock: inlineStatusSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(inlineStatusSchemaBlock, input),
    valid: { label: 'docs', status: 'ok', message: 'synced' },
    invalid: { label: 'docs' },
    requiredFields: ['label', 'status'],
    optionalFields: ['message'],
    expectedSlots: { label: 'docs', status: 'ok', message: 'synced' },
  },
  {
    block: inFlowStatusBlock,
    schemaBlock: inFlowStatusSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(inFlowStatusSchemaBlock, input),
    valid: {
      severity: 'warning',
      source: 'docs',
      message: 'inventory stale',
      action: 'run docs:inventory',
    },
    invalid: { severity: 'warning' },
    requiredFields: ['severity', 'message'],
    optionalFields: ['source', 'action'],
    expectedSlots: {
      severity: 'warning',
      source: 'docs',
      message: 'inventory stale',
      action: 'run docs:inventory',
    },
  },
  {
    block: transientOverlayBlock,
    schemaBlock: transientOverlaySchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(transientOverlaySchemaBlock, input),
    valid: {
      priority: 'normal',
      message: 'Saved DOGFOOD route',
      dismiss: 'Esc dismisses',
    },
    invalid: { priority: 'normal' },
    requiredFields: ['message'],
    optionalFields: ['priority', 'dismiss'],
    expectedSlots: {
      priority: 'normal',
      message: 'Saved DOGFOOD route',
      dismiss: 'Esc dismisses',
    },
  },
  {
    block: activityStreamBlock,
    schemaBlock: activityStreamSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(activityStreamSchemaBlock, input),
    valid: {
      events: ['10:41 tests passed', '10:42 PR opened'],
      selected: '10:41 tests passed',
    },
    invalid: { events: '10:41 tests passed' },
    requiredFields: ['events'],
    optionalFields: ['selected'],
    expectedSlots: {
      events: ['10:41 tests passed', '10:42 PR opened'],
      selected: '10:41 tests passed',
    },
  },
  {
    block: shortcutCueBlock,
    schemaBlock: shortcutCueSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(shortcutCueSchemaBlock, input),
    valid: { shortcuts: ['/ Search', '? Help', 'Esc Close'], scope: 'page' },
    invalid: { scope: 'page' },
    requiredFields: ['shortcuts'],
    optionalFields: ['scope'],
    expectedSlots: { shortcuts: ['/ Search', '? Help', 'Esc Close'], scope: 'page' },
  },
  {
    block: progressIndicatorBlock,
    schemaBlock: progressIndicatorSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(progressIndicatorSchemaBlock, input),
    valid: { label: 'Install packages', value: 3, total: 5, percent: '60%' },
    invalid: { label: 'Install packages', value: 3 },
    requiredFields: ['label', 'percent'],
    optionalFields: ['value', 'total'],
    expectedSlots: { label: 'Install packages', value: 3, total: 5, percent: '60%' },
  },
] as const;

export { STATUS_FEEDBACK_SCHEMA_BLOCKS };
