export const TRANCHE_A_ROOTS = [
  'packages/bijou-tui/src/eventbus.ts',
  'packages/bijou-tui/src/app-frame-actions.ts',
  'scripts/smoke-all-examples-lib.ts',
  'packages/bijou-i18n/src/runtime.ts',
  'packages/bijou-tui/src/timeline.ts',
] as const;

export const TRANCHE_A_PUBLIC_EXPORTS = {
  'packages/bijou-tui/src/eventbus.ts': [
    'BusMsg',
    'CommandBackpressureInfo',
    'CommandQueueDiagnostics',
    'CreateEventBusOptions',
    'EventBus',
    'Middleware',
    'createEventBus',
  ],
  'packages/bijou-tui/src/app-frame-actions.ts': [
    'applyDockMove',
    'applyFrameAction',
    'applyToggleMaximize',
    'applyToggleMinimize',
    'createTransitionTickCmd',
    'cyclePane',
    'scrollFocusedPane',
    'switchTab',
    'syncPageFrameState',
  ],
  'scripts/smoke-all-examples-lib.ts': [
    'DEFAULT_INPUT',
    'INTERACTIVE_FORM_SCRIPTS',
    'InteractiveScriptScenarioSpec',
    'PLAIN_INPUTS',
    'ROOT',
    'Result',
    'Scenario',
    'ScenarioMode',
    'SmokeAllExamplesIO',
    'SmokeRunOptions',
    'TOP_LEVEL',
    'buildSmokeScenarios',
    'createScenarioPlan',
    'isTuiTarget',
    'listExampleTargets',
    'parseSmokeRunOptions',
    'resolvePipeConcurrency',
    'runScenarioWithTimeout',
    'runSmokeAllExamples',
    'selectSmokeScenarios',
  ],
  'packages/bijou-i18n/src/runtime.ts': [
    'I18nCatalog',
    'I18nCatalogEntry',
    'I18nCatalogKey',
    'I18nCatalogLoader',
    'I18nDirection',
    'I18nEntryKind',
    'I18nFormatterPort',
    'I18nMissingMessageContext',
    'I18nMissingMessageFormatter',
    'I18nMissingReason',
    'I18nReference',
    'I18nRuntime',
    'I18nRuntimeOptions',
    'createI18nRuntime',
    'createI18nRuntimeAsync',
    'ref',
  ],
  'packages/bijou-tui/src/timeline.ts': [
    'Position',
    'SpringTrackDef',
    'Timeline',
    'TimelineBuilder',
    'TimelineState',
    'TrackDef',
    'TweenTrackDef',
    'timeline',
  ],
} as const satisfies Readonly<Record<
  (typeof TRANCHE_A_ROOTS)[number],
  readonly string[]
>>;
