import { TRANCHE_C_ROOTS } from './tranche-c-contract.js';

export const TRANCHE_C_FAMILY_MEMBERS = {
  'examples/_shared/canonical-app.ts': [
    'examples/_shared/canonical-app.ts',
    'examples/_shared/canonical-app-contract.ts',
    'examples/_shared/canonical-app-fixtures.ts',
    'examples/_shared/canonical-app-model.ts',
    'examples/_shared/canonical-app-format.ts',
    'examples/_shared/canonical-app-ops.ts',
    'examples/_shared/canonical-app-board.ts',
    'examples/_shared/canonical-app-graph.ts',
    'examples/_shared/canonical-app-page.ts',
    'examples/_shared/canonical-app-create.ts',
  ],
  'examples/notifications/main.ts': [
    'examples/notifications/main.ts',
    'examples/notifications/notification-demo-contract.ts',
    'examples/notifications/notification-demo-options.ts',
    'examples/notifications/notification-demo-state.ts',
    'examples/notifications/notification-demo-copy.ts',
    'examples/notifications/notification-demo-controls.ts',
    'examples/notifications/notification-demo-overlay.ts',
    'examples/notifications/notification-demo-mouse.ts',
    'examples/notifications/notification-demo-lifecycle.ts',
    'examples/notifications/notification-demo-create.ts',
    'examples/notifications/notification-demo-entry.ts',
  ],
  'examples/image-viewer/main.ts': [
    'examples/image-viewer/main.ts',
    'examples/image-viewer/image-viewer-contract.ts',
    'examples/image-viewer/image-viewer-options.ts',
    'examples/image-viewer/image-viewer-update.ts',
    'examples/image-viewer/image-viewer-files.ts',
    'examples/image-viewer/image-viewer-render.ts',
    'examples/image-viewer/image-viewer-preview.ts',
    'examples/image-viewer/image-viewer-tuning.ts',
    'examples/image-viewer/image-viewer-create.ts',
    'examples/image-viewer/image-viewer-entry.ts',
  ],
  'scripts/pr-review-status.ts': [
    'scripts/pr-review-status.ts',
    'scripts/pr-review-status-contract.ts',
    'scripts/pr-review-status-checks.ts',
    'scripts/pr-review-status-reviews.ts',
    'scripts/pr-review-status-coderabbit.ts',
    'scripts/pr-review-status-readiness.ts',
    'scripts/pr-review-status-github.ts',
    'scripts/pr-review-status-cli.ts',
  ],
  'packages/bijou-tui/src/app-frame-render.ts': [
    'packages/bijou-tui/src/app-frame-render.ts',
    'packages/bijou-tui/src/app-frame-render-contract.ts',
    'packages/bijou-tui/src/app-frame-render-colors.ts',
    'packages/bijou-tui/src/app-frame-render-node.ts',
    'packages/bijou-tui/src/app-frame-render-content.ts',
    'packages/bijou-tui/src/app-frame-render-header.ts',
    'packages/bijou-tui/src/app-frame-render-transition.ts',
    'packages/bijou-tui/src/app-frame-render-surface.ts',
    'packages/bijou-tui/src/app-frame-render-scratch.ts',
  ],
} as const satisfies Readonly<Record<
  (typeof TRANCHE_C_ROOTS)[number],
  readonly string[]
>>;
