export const TRANCHE_C_ROOTS = [
  'examples/_shared/canonical-app.ts',
  'examples/notifications/main.ts',
  'examples/image-viewer/main.ts',
  'scripts/pr-review-status.ts',
  'packages/bijou-tui/src/app-frame-render.ts',
] as const;

export const TRANCHE_C_PUBLIC_EXPORTS = {
  'examples/_shared/canonical-app.ts': ['createCanonicalWorkbenchApp'],
  'examples/notifications/main.ts': [
    'app',
    'createNotificationDemoApp',
    'ctx',
  ],
  'examples/image-viewer/main.ts': [
    'ImageRenderMode',
    'ImageTuningModel',
    'ImageViewerModel',
    'ImageViewerOptions',
    'ImageViewportModel',
    'createImageViewerApp',
    'main',
  ],
  'scripts/pr-review-status.ts': [
    'CheckEntry',
    'CheckSummary',
    'CodeRabbitStatus',
    'MergeReadiness',
    'PageInfo',
    'PullRequestComment',
    'PullRequestConnection',
    'PullRequestGraphqlResponse',
    'PullRequestReview',
    'ReviewSummary',
    'ReviewThreadComment',
    'ReviewThreadNode',
    'ReviewThreadsResponse',
    'UnresolvedFinding',
    'assertUntruncatedPullRequestData',
    'computeExitCode',
    'computeMergeReadiness',
    'computeMergeReadinessExitCode',
    'extractUnresolvedFindings',
    'mergeReadinessHeading',
    'summarizeChecks',
    'summarizeCodeRabbitStatus',
    'summarizeReviews',
  ],
  'packages/bijou-tui/src/app-frame-render.ts': [
    'FrameHeaderRenderResult',
    'FrameHeaderTabTarget',
    'FramePaneGeometryResult',
    'FramePaneScratchPool',
    'blockSurface',
    'createFramePaneScratchPool',
    'framePaneOutputToSurface',
    'renderFrameNode',
    'renderHelpLine',
    'renderMaximizedPane',
    'renderMaximizedPaneInto',
    'renderMissingGridCell',
    'renderPageContent',
    'renderPageContentInto',
    'renderTransition',
    'resolveHeaderLine',
  ],
} as const satisfies Readonly<Record<
  (typeof TRANCHE_C_ROOTS)[number],
  readonly string[]
>>;
