import { TRANCHE_E_ROOTS } from './tranche-e-contract.js';
import { TRANCHE_E_APP_FAMILY } from './tranche-e-app-family.js';
import { TRANCHE_E_STORY_FAMILY } from './tranche-e-story-family.js';

export const TRANCHE_E_FAMILY_MEMBERS = {
  'packages/bijou-tui/src/runtime-engine.ts': [
    'packages/bijou-tui/src/runtime-engine.ts',
    'packages/bijou-tui/src/runtime-engine-state.ts',
    'packages/bijou-tui/src/runtime-engine-view-stack.ts',
    'packages/bijou-tui/src/runtime-engine-layouts.ts',
    'packages/bijou-tui/src/runtime-engine-input.ts',
    'packages/bijou-tui/src/runtime-engine-component-layout.ts',
    'packages/bijou-tui/src/runtime-engine-component-contract.ts',
    'packages/bijou-tui/src/runtime-engine-hit-test.ts',
    'packages/bijou-tui/src/runtime-engine-route.ts',
    'packages/bijou-tui/src/runtime-engine-buffers.ts',
    'packages/bijou-tui/src/runtime-engine-component-create.ts',
    'packages/bijou-tui/src/runtime-engine-component-input.ts',
  ],
  'packages/bijou/src/core/components/table.ts': [
    'packages/bijou/src/core/components/table.ts',
    'packages/bijou/src/core/components/table-contract.ts',
    'packages/bijou/src/core/components/table-model.ts',
    'packages/bijou/src/core/components/table-measure.ts',
    'packages/bijou/src/core/components/table-normalize.ts',
    'packages/bijou/src/core/components/table-fit.ts',
    'packages/bijou/src/core/components/table-text-ansi.ts',
    'packages/bijou/src/core/components/table-cell-format.ts',
    'packages/bijou/src/core/components/table-build.ts',
    'packages/bijou/src/core/components/table-render-grid.ts',
    'packages/bijou/src/core/components/table-render-borderless.ts',
    'packages/bijou/src/core/components/table-render-markdown.ts',
    'packages/bijou/src/core/components/table-render-expanded.ts',
    'packages/bijou/src/core/components/table-render-visual.ts',
    'packages/bijou/src/core/components/table-render-pipe.ts',
  ],
  'packages/bijou-tui/src/app-frame.ts': [
    'packages/bijou-tui/src/app-frame.ts',
    'packages/bijou-tui/src/app-frame-app-init.ts',
    'packages/bijou-tui/src/app-frame-app-update.ts',
    'packages/bijou-tui/src/app-frame-app-view.ts',
    'packages/bijou-tui/src/app-frame-controls-runtime.ts',
    'packages/bijou-tui/src/app-frame-create.ts',
    'packages/bijou-tui/src/app-frame-frame-action-update.ts',
    'packages/bijou-tui/src/app-frame-help-keys.ts',
    'packages/bijou-tui/src/app-frame-help-scroll.ts',
    'packages/bijou-tui/src/app-frame-hint-sources.ts',
    'packages/bijou-tui/src/app-frame-host.ts',
    'packages/bijou-tui/src/app-frame-key-collision.ts',
    'packages/bijou-tui/src/app-frame-key-route-contract.ts',
    'packages/bijou-tui/src/app-frame-key-route-layers.ts',
    'packages/bijou-tui/src/app-frame-key-route-notifications.ts',
    'packages/bijou-tui/src/app-frame-key-route-palette-help.ts',
    'packages/bijou-tui/src/app-frame-key-route-settings.ts',
    'packages/bijou-tui/src/app-frame-key-route-shared.ts',
    'packages/bijou-tui/src/app-frame-key-route-workspace.ts',
    'packages/bijou-tui/src/app-frame-key-route.ts',
    'packages/bijou-tui/src/app-frame-layer-context.ts',
    'packages/bijou-tui/src/app-frame-layer-metadata.ts',
    'packages/bijou-tui/src/app-frame-layout-contract.ts',
    'packages/bijou-tui/src/app-frame-layout-runtime.ts',
    'packages/bijou-tui/src/app-frame-model-helpers.ts',
    'packages/bijou-tui/src/app-frame-mouse-layout.ts',
    'packages/bijou-tui/src/app-frame-mouse-route.ts',
    'packages/bijou-tui/src/app-frame-mouse-workspace.ts',
    'packages/bijou-tui/src/app-frame-notification-contract.ts',
    'packages/bijou-tui/src/app-frame-notification-runtime.ts',
    'packages/bijou-tui/src/app-frame-notification-state.ts',
    'packages/bijou-tui/src/app-frame-options.ts',
    'packages/bijou-tui/src/app-frame-page-contract.ts',
    'packages/bijou-tui/src/app-frame-page-registry.ts',
    'packages/bijou-tui/src/app-frame-page-update.ts',
    'packages/bijou-tui/src/app-frame-performance-runtime.ts',
    'packages/bijou-tui/src/app-frame-performance.ts',
    'packages/bijou-tui/src/app-frame-presentation.ts',
    'packages/bijou-tui/src/app-frame-runtime.ts',
    'packages/bijou-tui/src/app-frame-settings-contract.ts',
    'packages/bijou-tui/src/app-frame-shell-command-contract.ts',
    'packages/bijou-tui/src/app-frame-shell-command-interaction.ts',
    'packages/bijou-tui/src/app-frame-shell-command-ui.ts',
    'packages/bijou-tui/src/app-frame-shell-command.ts',
    'packages/bijou-tui/src/app-frame-theme-contract.ts',
    'packages/bijou-tui/src/app-frame-theme-mode.ts',
    'packages/bijou-tui/src/app-frame-theme-run-contract.ts',
    'packages/bijou-tui/src/app-frame-theme-runtime.ts',
    'packages/bijou-tui/src/app-frame-transition-contract.ts',
    'packages/bijou-tui/src/app-frame-transition-update.ts',
    'packages/bijou-tui/src/app-frame-view-base.ts',
    'packages/bijou-tui/src/app-frame-view-body.ts',
    'packages/bijou-tui/src/app-frame-view-contract.ts',
    'packages/bijou-tui/src/app-frame-view-modals.ts',
    'packages/bijou-tui/src/app-frame-view-overlays.ts',
    'packages/bijou-tui/src/app-frame-workspace-layout.ts',
    'packages/bijou-tui/src/app-frame-workspace-tree.ts',
  ],
  'examples/docs/app.ts': TRANCHE_E_APP_FAMILY,
  'examples/docs/stories.ts': TRANCHE_E_STORY_FAMILY,
} as const satisfies Readonly<
  Record<(typeof TRANCHE_E_ROOTS)[number], readonly string[]>
>;
