import { TRANCHE_D_ROOTS } from './tranche-d-contract.js';

export const TRANCHE_D_FAMILY_MEMBERS = {
  'packages/bijou/src/ports/surface.ts': [
    'packages/bijou/src/ports/surface.ts',
    'packages/bijou/src/ports/surface-cell.ts',
    'packages/bijou/src/ports/surface-layout.ts',
    'packages/bijou/src/ports/surface-transform.ts',
    'packages/bijou/src/ports/surface-contract.ts',
    'packages/bijou/src/ports/surface-packed-color.ts',
    'packages/bijou/src/ports/surface-packed-codec.ts',
    'packages/bijou/src/ports/surface-packed-state.ts',
    'packages/bijou/src/ports/surface-packed-write.ts',
    'packages/bijou/src/ports/surface-packed-compose.ts',
    'packages/bijou/src/ports/surface-packed-read.ts',
    'packages/bijou/src/ports/surface-create.ts',
  ],
  'examples/docs/i18n-debt.ts': [
    'examples/docs/i18n-debt.ts',
    'examples/docs/i18n-debt-contract.ts',
    'examples/docs/i18n-debt-sources.ts',
    'examples/docs/i18n-debt-ratchet.ts',
    'examples/docs/i18n-debt-source-scan.ts',
    'examples/docs/i18n-debt-source-context.ts',
    'examples/docs/i18n-debt-markdown-discovery.ts',
    'examples/docs/i18n-debt-markdown-spec.ts',
    'examples/docs/i18n-debt-markdown-ratchet.ts',
    'examples/docs/i18n-debt-io.ts',
  ],
  'packages/bijou-tui/src/app-frame-overlays.ts': [
    'packages/bijou-tui/src/app-frame-overlays.ts',
    'packages/bijou-tui/src/app-frame-overlay-contract.ts',
    'packages/bijou-tui/src/app-frame-overlay-help.ts',
    'packages/bijou-tui/src/app-frame-overlay-shell-theme.ts',
    'packages/bijou-tui/src/app-frame-overlay-settings.ts',
    'packages/bijou-tui/src/app-frame-overlay-notifications.ts',
    'packages/bijou-tui/src/app-frame-overlay-layout.ts',
    'packages/bijou-tui/src/app-frame-overlay-navigation.ts',
    'packages/bijou-tui/src/app-frame-overlay-render-settings.ts',
    'packages/bijou-tui/src/app-frame-overlay-render-notifications.ts',
  ],
  'packages/bijou/src/core/ui-scene-ir.ts': [
    'packages/bijou/src/core/ui-scene-ir.ts',
    'packages/bijou/src/core/ui-scene-contract.ts',
    'packages/bijou/src/core/ui-scene-target-profile.ts',
    'packages/bijou/src/core/ui-scene-canonical.ts',
    'packages/bijou/src/core/ui-scene-validation.ts',
    'packages/bijou/src/core/ui-scene-receipt.ts',
    'packages/bijou/src/core/ui-scene-lowering.ts',
    'packages/bijou/src/core/ui-scene-terminal-proof.ts',
    'packages/bijou/src/core/ui-scene-lowering-utils.ts',
  ],
  'packages/bijou/src/core/render/differ.ts': [
    'packages/bijou/src/core/render/differ.ts',
    'packages/bijou/src/core/render/differ-ansi.ts',
    'packages/bijou/src/core/render/differ-string.ts',
    'packages/bijou/src/core/render/differ-paint.ts',
    'packages/bijou/src/core/render/differ-cell.ts',
    'packages/bijou/src/core/render/differ-packed-bytes.ts',
    'packages/bijou/src/core/render/differ-packed.ts',
    'packages/bijou/src/core/render/differ-cells.ts',
  ],
} as const satisfies Readonly<
  Record<(typeof TRANCHE_D_ROOTS)[number], readonly string[]>
>;
