/** Internal dependency facade for DOGFOOD component stories. */

export type { BijouContext } from '@flyingrobots/bijou';
export {
  accordion,
  alert,
  box,
  boxSurface,
  brailleChartSurface,
  breadcrumb,
  createSurface,
  dag,
  enumeratedList,
  explainability,
  guidedFlow,
  gradientText,
  headerBox,
  hyperlink,
  inspector,
  kbd,
  loadRandomLogo,
  log,
  markdown,
  paginator,
  perfOverlaySurface,
  progressBar,
  renderByMode,
  separator,
  separatorSurface,
  skeleton,
  sparkline,
  spinnerFrame,
  statsPanelSurface,
  stepper,
  table,
  tabs,
  timeline as processTimeline,
  tree,
  type Surface,
  type TableColumn,
  type TablePipeFormat,
  type TableVariant,
} from '@flyingrobots/bijou';
export {
  canvas,
  compositeSurface,
  browsableListSurface,
  cpFilter,
  createKeyMap,
  createAccordionState,
  createBrowsableListState,
  createCommandPaletteState,
  createNavigableTableState,
  createNotificationState,
  createSplitPaneState,
  dismissNotification,
  drawer,
  filePickerSurface,
  gridSurface,
  helpShort,
  helpShortSurface,
  helpView,
  helpViewSurface,
  interactiveAccordion,
  modal,
  navigableTableSurface,
  pushNotification,
  renderNotificationHistory,
  renderNotificationHistorySurface,
  renderNotificationStack,
  splitPaneSurface,
  statusBarSurface,
  tickNotifications,
  toast,
  tooltip,
  commandPaletteSurface,
  createSpringState,
  raytraceDot,
  raytraceNearestHit,
  raytraceNormalize,
  raytraceOrbitCameraRay,
  raytraceReflect,
  resolveSpringConfig,
  springStep,
  timeline as motionTimeline,
  type RaytraceShape,
} from '../../packages/bijou-tui/src/index.js';
export {
  badgeSurface,
  column,
  contentSurface,
  line,
  row,
  screenSurface,
  spacer,
} from '../_shared/example-surfaces.js';
export {
  CANONICAL_STORY_PROFILE_PRESETS,
  type ComponentStory,
} from '../_stories/protocol.js';
export { confirmPreview } from './story-preview-confirm.js';
export {
  LONG_DOCUMENT,
  MARKDOWN_RELEASE_NOTES,
} from './story-preview-documents.js';
export {
  modalBackdrop,
  pagerPreviewSurface,
  toastBackdrop,
  viewportPreviewSurface,
} from './story-preview-layout.js';
export { focusedPanePreviewSurface } from './story-preview-focus.js';
export { multiselectPreview } from './story-preview-multiselect.js';
export {
  filterPreview,
  selectPreview,
} from './story-preview-single-select.js';
export {
  dogfoodText,
  infoText,
  mutedText,
} from './story-preview-style.js';
