import { binaryDecisionBlock, binaryDecisionSchemaBlock, bindSchemaBlockInput, multipleChoiceBlock, multipleChoiceSchemaBlock, pathProgressBlock, pathProgressSchemaBlock, peerNavigationBlock, peerNavigationSchemaBlock, progressiveDisclosureBlock, progressiveDisclosureSchemaBlock, singleChoiceBlock, singleChoiceSchemaBlock } from '../../../packages/bijou/src/index.js';

const CHOICE_NAVIGATION_SCHEMA_BLOCKS = [
  {
    block: singleChoiceBlock,
    schemaBlock: singleChoiceSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(singleChoiceSchemaBlock, input),
    valid: {
      label: 'Output mode',
      options: ['interactive', 'pipe', 'accessible'],
      selected: 'pipe',
      mode: 'radio',
      validation: 'available',
    },
    invalid: { label: 'Output mode' },
    requiredFields: ['label', 'options', 'selected'],
    optionalFields: ['mode', 'validation'],
    expectedSlots: {
      label: 'Output mode',
      options: ['interactive', 'pipe', 'accessible'],
      selected: 'pipe',
      mode: 'radio',
      validation: 'available',
    },
  },
  {
    block: multipleChoiceBlock,
    schemaBlock: multipleChoiceSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(multipleChoiceSchemaBlock, input),
    valid: {
      label: 'Release proof',
      checked: ['lint', 'tests'],
      unchecked: ['screenshots'],
      selected: 'lint; tests',
      validation: '2 of 3 complete',
    },
    invalid: { label: 'Release proof', checked: ['lint'] },
    requiredFields: ['label', 'checked', 'unchecked'],
    optionalFields: ['selected', 'validation'],
    expectedSlots: {
      label: 'Release proof',
      checked: ['lint', 'tests'],
      unchecked: ['screenshots'],
      selected: 'lint; tests',
      validation: '2 of 3 complete',
    },
  },
  {
    block: binaryDecisionBlock,
    schemaBlock: binaryDecisionSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(binaryDecisionSchemaBlock, input),
    valid: {
      label: 'Merge gate',
      selected: 'yes',
      consequence: 'admin merge',
      confirmation: 'CI green',
      disabledReason: 'none',
    },
    invalid: { label: 'Merge gate' },
    requiredFields: ['label', 'selected', 'consequence'],
    optionalFields: ['confirmation', 'disabledReason'],
    expectedSlots: {
      label: 'Merge gate',
      selected: 'yes',
      consequence: 'admin merge',
      confirmation: 'CI green',
      disabledReason: 'none',
    },
  },
  {
    block: peerNavigationBlock,
    schemaBlock: peerNavigationSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(peerNavigationSchemaBlock, input),
    valid: {
      previous: 'Architecture',
      current: 'Blocks',
      next: 'Method',
      route: 'docs/blocks',
      status: 'available',
    },
    invalid: { current: 'Blocks' },
    requiredFields: ['previous', 'current', 'next'],
    optionalFields: ['route', 'status'],
    expectedSlots: {
      previous: 'Architecture',
      current: 'Blocks',
      next: 'Method',
      route: 'docs/blocks',
      status: 'available',
    },
  },
  {
    block: progressiveDisclosureBlock,
    schemaBlock: progressiveDisclosureSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(progressiveDisclosureSchemaBlock, input),
    valid: {
      label: 'Advanced options',
      state: 'closed',
      hiddenCount: 6,
      summary: '6 options hidden',
      details: ['debug traces', 'layout facts'],
    },
    invalid: { label: 'Advanced options', state: 'closed' },
    requiredFields: ['label', 'state', 'hiddenCount'],
    optionalFields: ['summary', 'details'],
    expectedSlots: {
      label: 'Advanced options',
      state: 'closed',
      hiddenCount: 6,
      summary: '6 options hidden',
      details: ['debug traces', 'layout facts'],
    },
  },
  {
    block: pathProgressBlock,
    schemaBlock: pathProgressSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(pathProgressSchemaBlock, input),
    valid: {
      path: ['Setup', 'Blocks', 'Preview'],
      current: 'Blocks',
      step: 2,
      total: 3,
      status: 'current',
    },
    invalid: { current: 'Blocks', step: 2 },
    requiredFields: ['path', 'current', 'step', 'total'],
    optionalFields: ['status'],
    expectedSlots: {
      path: ['Setup', 'Blocks', 'Preview'],
      current: 'Blocks',
      step: 2,
      total: 3,
      status: 'current',
    },
  },
] as const;

export { CHOICE_NAVIGATION_SCHEMA_BLOCKS };
