/**
 * @module @flyingrobots/bijou
 *
 * Themed terminal components for CLIs, loggers, and scripts —
 * with graceful degradation across output modes.
 */

// Port interfaces
export type {
  RuntimePort,
  WritePort,
  QueryPort,
  InteractivePort,
  FilePort,
  IOPort,
  ClockPort,
  RawInputHandle,
  TimerHandle,
  KeyInputMsg,
  StylePort,
  BijouContext,
} from './ports/index.js';

export {
  type Cell,
  type Surface,
  type PackedSurface,
  type CellMask,
  type Matrix3x3,
  type TransformOptions,
  createSurface,
  isPackedSurface,
  FULL_MASK,
  ROTATION_CHAR_MAP,
} from './ports/surface.js';

export {
  FLAG_BOLD,
  FLAG_DIM,
  FLAG_STRIKETHROUGH,
  FLAG_INVERSE,
  FLAG_EMPTY,
  UNDERLINE_SOLID,
  UNDERLINE_CURLY,
  UNDERLINE_DOTDASH,
  FLAG_DASHED,
} from './core/render/packed-cell.js';

// Context
export {
  getDefaultContext,
  setDefaultContext,
  setDefaultContextInitializer,
} from './context.js';
export {
  cloneContextWithResolvedTheme,
  cloneContextWithTheme,
  observeTheme,
  type ThemeChange,
  type ThemeObservation,
} from './context-theme.js';

// Context resolution helpers
export { resolveCtx, resolveSafeCtx } from './core/resolve-ctx.js';
export { systemClock, resolveClock, sleep, defer } from './core/clock.js';
export { decodeRawKeyInput, decodeRawKeySequence } from './core/key-input.js';
export {
  type RuntimeViewport,
  sanitizeRuntimeDimension,
  readRuntimeViewport,
  installRuntimeViewportOverlay,
  updateRuntimeViewport,
} from './core/runtime-viewport.js';
export {
  sanitizeNonNegativeInt,
  sanitizeOptionalNonNegativeInt,
  sanitizeOptionalPositiveInt,
  sanitizePositiveInt,
} from './core/numeric.js';
export {
  solveGridRects,
  solveSplitAxisSizes,
  solveSplitPaneRects,
  type GridTrack,
  type SplitAxisOptions,
  type SplitAxisSizes,
  type SplitLayoutDirection,
  type SplitPaneRectOptions,
  type SplitPaneRects,
  type GridRectOptions,
} from './core/layout/geometry.js';

// Mode rendering strategy
export {
  renderByMode,
  type ModeHandler,
  type ModeMap,
} from './core/mode-render.js';
export {
  BindingFrame,
  bindingFrame,
  bindingFrameFromSnapshots,
  bindingSnapshot,
  commandIntent,
  defineDataRequirement,
  defineDataProvider,
  defineViewData,
  isBindingSnapshot,
  isCommandIntent,
  isDataProvider,
  isDataRequirement,
  isProviderResolution,
  isProviderScope,
  isViewDataContract,
  provide,
  providerScope,
  ProviderScope,
  resolveProviderRequirement,
  resolveProviderRequirements,
  ViewDataContract,
  type BindingFact,
  type BindingIssue,
  type BindingIssueSeverity,
  type BindingFrameAssembly,
  type BindingFrameFromSnapshotsInput,
  type BindingSnapshot,
  type BindingSnapshotInput,
  type BindingStatus,
  type CommandIntent,
  type CommandIntentId,
  type CommandIntentOptions,
  type DataProvider,
  type DataProviderInput,
  type DataRequirement,
  type DataRequirementInput,
  type DeepReadonly,
  type ProviderId,
  type ProviderResolution,
  type ProviderResolutionStatus,
  type ProviderScopeEntry,
  type ProviderScopeOptions,
  type RequirementId,
  type ViewDataInput,
  type ViewDataRequirementEntry,
} from './core/binding.js';
export {
  AppShellComposition,
  defineAppShellComposition,
  isAppShellComposition,
  type AppShellCompositionInput,
  type AppShellSlot,
  type AppShellSlotContent,
  type AppShellSlotId,
  type AppShellSlots,
} from './core/app-shell-composition.js';
export {
  blockMetadataReportText,
  blockMetadataSummary,
  blockPackageManifestReportText,
  blockPackageManifestSummary,
  defineBlock,
  defineBlockPackage,
  isBlockDefinition,
  validateBlockMetadata,
  validateBlockPackageManifest,
  type BlockConfigOption,
  type BlockConfigOptionKind,
  type BlockDefinition,
  type BlockDefinitionInput,
  type BlockExample,
  type BlockMetadata,
  type BlockMetadataDocs,
  type BlockMetadataIssue,
  type BlockMetadataIssueKind,
  type BlockMetadataReport,
  type BlockMetadataSeverity,
  type BlockPackageManifest,
  type BlockPackageManifestReport,
  type BlockRenderInput,
  type BlockRenderResult,
  type BlockScale,
  type BlockSlot,
  type BlockVariantMetadata,
} from './core/block-metadata.js';
export {
  componentMetadataReportText,
  componentMetadataSummary,
  defineComponentMetadata,
  validateComponentMetadata,
  type ComponentMetadata,
  type ComponentMetadataArg,
  type ComponentMetadataDocs,
  type ComponentMetadataExample,
  type ComponentMetadataInvariant,
  type ComponentMetadataIssue,
  type ComponentMetadataIssueKind,
  type ComponentMetadataReport,
  type ComponentMetadataSeverity,
  type ComponentMetadataVariant,
} from './core/component-metadata.js';
export {
  captureStoryMatrix,
  storyCaptureMatrixText,
  type StoryCapture,
  type StoryCaptureMatrix,
  type StoryCaptureMatrixOptions,
  type StoryCaptureProfile,
  type StoryCaptureRenderInput,
  type StoryCaptureVariant,
} from './core/story-capture.js';
export {
  createFixturePromotionRecord,
  fixturePromotionText,
  reverseFixturePromotionRecord,
  type FixturePromotionArtifact,
  type FixturePromotionArtifactKind,
  type FixturePromotionRecord,
  type FixturePromotionRecordOptions,
  type ReverseFixturePromotionOptions,
} from './core/fixture-promotion.js';
export {
  lintModeLowering,
  modeLoweringReportText,
  type ModeLoweringAssertionResult,
  type ModeLoweringFact,
  type ModeLoweringFactKind,
  type ModeLoweringFactValue,
  type ModeLoweringIssue,
  type ModeLoweringIssueKind,
  type ModeLoweringModeFacts,
  type ModeLoweringOptions,
  type ModeLoweringReport,
  type ModeLoweringSeverity,
} from './core/mode-lowering.js';

// Background fill utilities
export { shouldApplyBg, makeBgFill } from './core/bg-fill.js';

// Factory
export { createBijou, type CreateBijouOptions } from './factory.js';

// Theme engine
export {
  // Types
  type RGB,
  type GradientStop,
  type TextModifier,
  type TokenValue,
  type InkColor,
  type BaseStatusKey,
  type BaseUiKey,
  type BaseGradientKey,
  type Theme,
  // Presets
  CYAN_MAGENTA,
  TEAL_ORANGE_PINK,
  PRESETS,
  tv,
  // Freestanding styled helpers
  styled,
  styledStatus,
  // Theme extension
  extendTheme,
  // Theme doctor
  doctorTheme,
  themeContrastRatio,
  type ThemeContrastPair,
  type ThemeDoctorIssue,
  type ThemeDoctorIssueKind,
  type ThemeDoctorOptions,
  type ThemeDoctorReport,
  type ThemeDoctorSeverity,
  // Gradient
  lerp3,
  gradientText,
  // Gradient options
  type GradientTextOptions,
  // Resolver
  isNoColor,
  createThemeResolver,
  createResolved,
  type ResolvedTheme,
  type ThemeResolver,
  type ThemeResolverOptions,
  // DTCG interop
  fromDTCG,
  toDTCG,
  type DTCGDocument,
  type DTCGToken,
  type DTCGGroup,
  // Color downsampling
  rgbToAnsi256,
  nearestAnsi256,
  rgbToAnsi16,
  ansi256ToAnsi16,
  type ColorLevel,
  // Theme accessors
  createThemeAccessors,
  type ThemeAccessors,
  // Color manipulation
  color,
  colorHex,
  colorRgb,
  hexToRgb,
  isResolvedColor,
  resolveColor,
  rgbToHex,
  tryResolveColor,
  lighten,
  darken,
  mix,
  complementary,
  saturate,
  desaturate,
  type ColorRef,
  type ResolvedColor,
  // Reactive Token Graph
  createTokenGraph,
  type TokenGraph,
  type ThemeMode,
  type ColorDefinition,
  type TokenDefinition,
  type TokenDefinitions,
  type ColorTransform,
} from './core/theme/index.js';

// Text / grapheme utilities
export {
  forceTextPresentation,
  TEXT_PRESENTATION_SELECTOR,
  isWideChar,
  segmentGraphemes,
  graphemeClusterWidth,
  graphemeWidth,
  sanitizeTerminalText,
  sanitizePlainTerminalText,
  prepareWrappedText,
  wrapPreparedTextToWidth,
  clipToWidth,
  wrapToWidth,
  ANSI_CONTROL_SEQUENCE_RE,
  ANSI_SGR_RE,
  stripAnsi,
} from './core/text/index.js';
export type {
  PreparedWrappedLine,
  PreparedWrappedText,
} from './core/text/index.js';

// Detection
export {
  detectOutputMode,
  detectColorScheme,
  type OutputMode,
  type ColorScheme,
} from './core/detect/index.js';

// Components
export {
  spinnerFrame,
  createSpinner,
  type SpinnerOptions,
  type SpinnerController,
  type OverflowBehavior,
  progressBar,
  createProgressBar,
  createAnimatedProgressBar,
  type ProgressBarOptions,
  type LiveProgressBarOptions,
  type AnimatedProgressBarOptions,
  type ProgressBarController,
  table,
  type TableColumn,
  type TableTextCell,
  type TableTextRow,
  type TableOptions,
  tableSurface,
  type TableSurfaceCell,
  type TableSurfaceRow,
  type TableSurfaceOptions,
  box,
  headerBox,
  type BoxOptions,
  type HeaderBoxOptions,
  boxSurface,
  headerBoxSurface,
  selectLogoSize,
  loadRandomLogo,
  type LogoSize,
  type LogoResult,
  type LogoConstraints,
  type LogoOptions,
  separator,
  type SeparatorOptions,
  separatorSurface,
  badge,
  type BadgeVariant,
  type BadgeOptions,
  alert,
  type AlertVariant,
  type AlertOptions,
  alertSurface,
  skeleton,
  type SkeletonOptions,
  kbd,
  type KbdOptions,
  tree,
  type TreeNode,
  type TreeOptions,
  accordion,
  type AccordionSection,
  type AccordionOptions,
  timeline,
  type TimelineEvent,
  type TimelineOptions,
  tabs,
  type TabItem,
  type TabsOptions,
  breadcrumb,
  type BreadcrumbOptions,
  paginator,
  type PaginatorOptions,
  stepper,
  type StepperStep,
  type StepperOptions,
  guidedFlow,
  type GuidedFlowStepStatus,
  type GuidedFlowStep,
  type GuidedFlowSectionTone,
  type GuidedFlowSection,
  type GuidedFlowOptions,
  explainability,
  type ExplainabilityEvidenceItem,
  type ExplainabilityOptions,
  inspector,
  type InspectorChrome,
  type InspectorSectionTone,
  type InspectorSection,
  type InspectorOptions,
  dag,
  dagSlice,
  dagLayout,
  type DagCompactShape,
  type DagEdgeStyle,
  type DagNode,
  type DagOptions,
  type DagNodePosition,
  type DagNodeStyle,
  type DagLayout,
  arraySource,
  isDagSource,
  isSlicedDagSource,
  type DagSource,
  type SlicedDagSource,
  type DagSliceOptions,
  dagStats,
  type DagStats,
  enumeratedList,
  type BulletStyle,
  type EnumeratedListOptions,
  hyperlink,
  type HyperlinkOptions,
  log,
  type LogLevel,
  type LogOptions,
  markdown,
  type MarkdownOptions,
  constrain,
  type ConstrainOptions,
  timer,
  createTimer,
  createStopwatch,
  type TimerOptions,
  type TimerController,
  type CreateTimerOptions,
  type CreateStopwatchOptions,
  cursorGuard,
  withHiddenCursor,
  type CursorGuard,
  type CursorHideHandle,
  sparkline,
  type SparklineOptions,
  brailleChartSurface,
  type BrailleChartOptions,
  statsPanelSurface,
  type StatsPanelEntry,
  type StatsPanelOptions,
  perfOverlaySurface,
  type PerfOverlayStats,
  type PerfOverlayOptions,
} from './core/components/index.js';

export {
  preferenceListSurface,
  preferenceRowSurface,
  resolvePreferenceRowLayout,
  preparePreferenceRow,
  preparePreferenceSections,
} from './core/components/preference-list.js';
export type {
  PreferenceListTheme,
  PreferenceRowKind,
  PreferenceRow,
  PreparedPreferenceRow,
  PreferenceSection,
  PreparedPreferenceSection,
  PreferenceRowLayout,
  PreferenceRowSurfaceOptions,
  PreferenceListSurfaceOptions,
} from './core/components/preference-list.js';

// Shared ANSI escape constants
export { HIDE_CURSOR, SHOW_CURSOR, CLEAR_LINE_RETURN } from './core/ansi.js';

// Rendering
export { renderDiff, isSameCell, stringToSurface, parseAnsiToSurface, surfaceToString, paintLayoutNode } from './core/render/differ.js';

// Layout
export type { LayoutRect, LayoutNode, LayoutEngine } from './ports/surface.js';
export { calculateFlex, type FlexOptions, type FlexChildProps } from './core/layout/flex.js';

// Forms
export {
  type ValidationResult,
  type Validator,
  type FieldOptions,
  type SelectOption,
  type SelectFieldOptions,
  type ConfirmFieldOptions,
  type GroupFieldResult,
  type InputOptions,
  input,
  select,
  multiselect,
  confirm,
  group,
  textarea,
  type TextareaOptions,
  filter,
  type FilterOption,
  type FilterOptions,
  wizard,
  type WizardStep,
  type WizardOptions,
  note,
  type NoteOptions,
} from './core/forms/index.js';
