// Theme engine
export {
  // Types
  type RGB,
  type GradientStop,
  type TextModifier,
  type TokenValue,
  type InkColor,
  type BaseStatusKey,
  type BaseUiKey,
  type BaseGradientKey,
  type Theme,
  defineTheme,
  isTokenRef,
  resolveThemeColorRef,
  tokenRef,
  type ResolveThemeColorRefOptions,
  type ThemeBuilder,
  type ThemeBuilderModeId,
  type ThemeBuilderRequiredMode,
  type ThemeColorInput,
  type ThemeColorRef,
  type ThemeColorResolution,
  type ThemeColorTokenValue,
  type ThemeModeBuilder,
  type ThemeModeTokenColorBuilder,
  type ThemeModeTokenDraftBuilder,
  type ThemeModeTokenIdBuilder,
  type ThemeModeTokenRegistrationBuilder,
  type ThemeRgbObject,
  type ThemeTokenRef,
  type TokenTheme,
  type TokenThemeMode,
  // Presets
  BIJOU_DARK,
  BIJOU_LIGHT,
  CYAN_MAGENTA,
  TEAL_ORANGE_PINK,
  PRESETS,
  tv,
  // Theme extension
  extendTheme,
  // Theme doctor
  defineThemeSafePairs,
  doctorTheme,
  themeContrastRatio,
  type ThemeContrastPair,
  type ThemeDoctorIssue,
  type ThemeDoctorIssueKind,
  type ThemeDoctorOptions,
  type ThemeDoctorReport,
  type ThemeDoctorSeverity,
  type ThemeSafePair,
  type ThemeSafePairBuilder,
  type ThemeSafePairKind,
  type ThemeSafePairOptions,
  // Gradient
  lerp3,
  gradientText,
  // Gradient options
  type GradientTextOptions,
  // Resolver
  isNoColor,
  createThemeResolver,
  createResolved,
  type ResolvedTheme,
  type ThemeResolver,
  type ThemeResolverOptions,
  // DTCG interop
  fromDTCG,
  toDTCG,
  type DTCGDocument,
  type DTCGToken,
  type DTCGGroup,
  // Color downsampling
  rgbToAnsi256,
  nearestAnsi256,
  rgbToAnsi16,
  ansi256ToAnsi16,
  type ColorLevel,
  // Theme accessors
  createThemeAccessors,
  type ThemeAccessors,
  // Color manipulation
  color,
  colorHex,
  colorRgb,
  hexToRgb,
  isResolvedColor,
  resolveColor,
  rgbToHex,
  tryResolveColor,
  lighten,
  darken,
  mix,
  complementary,
  saturate,
  desaturate,
  type ColorRef,
  type ResolvedColor,
  // Reactive Token Graph
  createTokenGraph,
  type TokenGraph,
  type ThemeMode,
  type ColorDefinition,
  type TokenDefinition,
  type TokenDefinitions,
  type ColorTransform,
} from './core/theme/index.js';

export * from './core/theme/styled.js';

// Text / grapheme utilities
export {
  forceTextPresentation,
  TEXT_PRESENTATION_SELECTOR,
  isWideChar,
  segmentGraphemes,
  graphemeClusterWidth,
  graphemeWidth,
  sanitizeTerminalText,
  sanitizePlainTerminalText,
  prepareWrappedText,
  wrapPreparedTextToWidth,
  clipToWidth,
  wrapToWidth,
  ANSI_CONTROL_SEQUENCE_RE,
  ANSI_SGR_RE,
  stripAnsi,
} from './core/text/index.js';
