export {
  type RGB,
  type GradientStop,
  type TextModifier,
  type TokenValue,
  type InkColor,
  type BaseStatusKey,
  type BaseUiKey,
  type BaseGradientKey,
  type Theme,
  defineTheme,
  isTokenRef,
  resolveThemeColorRef,
  tokenRef,
  type ResolveThemeColorRefOptions,
  type ThemeBuilder,
  type ThemeBuilderModeId,
  type ThemeBuilderRequiredMode,
  type ThemeColorInput,
  type ThemeColorRef,
  type ThemeColorResolution,
  type ThemeColorTokenValue,
  type ThemeModeBuilder,
  type ThemeModeTokenColorBuilder,
  type ThemeModeTokenDraftBuilder,
  type ThemeModeTokenIdBuilder,
  type ThemeModeTokenRegistrationBuilder,
  type ThemeRgbObject,
  type ThemeTokenRef,
  type TokenTheme,
  type TokenThemeMode,
  BIJOU_DARK,
  BIJOU_LIGHT,
  CYAN_MAGENTA,
  TEAL_ORANGE_PINK,
  PRESETS,
  tv,
  extendTheme,
  defineThemeSafePairs,
  doctorTheme,
  themeContrastRatio,
  type ThemeContrastPair,
  type ThemeDoctorIssue,
  type ThemeDoctorIssueKind,
  type ThemeDoctorOptions,
  type ThemeDoctorReport,
  type ThemeDoctorSeverity,
  type ThemeSafePair,
  type ThemeSafePairBuilder,
  type ThemeSafePairKind,
  type ThemeSafePairOptions,
  lerp3,
  gradientText,
  type GradientTextOptions,
  isNoColor,
  createThemeResolver,
  createResolved,
  type ResolvedTheme,
  type ThemeResolver,
  type ThemeResolverOptions,
  fromDTCG,
  toDTCG,
  type DTCGDocument,
  type DTCGToken,
  type DTCGGroup,
  rgbToAnsi256,
  nearestAnsi256,
  rgbToAnsi16,
  ansi256ToAnsi16,
  type ColorLevel,
  createThemeAccessors,
  type ThemeAccessors,
  color,
  colorHex,
  colorRgb,
  hexToRgb,
  isResolvedColor,
  resolveColor,
  rgbToHex,
  tryResolveColor,
  lighten,
  darken,
  mix,
  complementary,
  saturate,
  desaturate,
  type ColorRef,
  type ResolvedColor,
  createTokenGraph,
  bestContrastWith,
  closestColor,
  colorCandidate,
  isThemeColorRuleDefinition,
  leastVivid,
  minContrastWith,
  mostVivid,
  nthColor,
  scope,
  tokenCandidate,
  type TokenGraph,
  type ThemeMode,
  type ColorDefinition,
  type TokenDefinition,
  type TokenDefinitions,
  type ColorTransform,
  type MinContrastRuleOptions,
  type VividRuleOptions,
  type ThemeColorRuleDefinition,
  type ThemeRuleCandidateInput,
  type ThemeRuleCandidateInspection,
  type ThemeRuleCandidateReason,
  type ThemeRuleCandidateScope,
  type ThemeRuleCandidateSource,
  type ThemeRuleCandidatePath,
  type ThemeRuleCandidateValue,
  type ThemeRuleInspection,
  type ThemeTokenInspection,
  type TokenGraphInspection,
} from './core/theme/index.js';

export * from './core/theme/styled.js';

// Text / grapheme utilities
export {
  forceTextPresentation,
  TEXT_PRESENTATION_SELECTOR,
  isWideChar,
  segmentGraphemes,
  graphemeClusterWidth,
  graphemeWidth,
  sanitizeTerminalText,
  sanitizePlainTerminalText,
  prepareWrappedText,
  wrapPreparedTextToWidth,
  clipToWidth,
  wrapToWidth,
  ANSI_CONTROL_SEQUENCE_RE,
  ANSI_SGR_RE,
  stripAnsi,
} from './core/text/index.js';
