export {
  RE035_LAYOUT_SCOPE,
  assignLayoutChild,
  assignedLayoutRect,
  contentExtentFromBuffer,
  contentExtentFromSurface,
  defineLayoutEnvelope,
  isResolvedLayoutEnvelope,
  layoutConstraints,
  layoutExplanationFacts,
  layoutExplanationText,
  layoutPreference,
  measureTextContent,
  placeInRect,
  renderWithResolvedLayout,
  resolveStackLayout,
  type AssignedLayoutRect,
  type AssignedLayoutRectInput,
  type ContentExtent,
  type ContentExtentInput,
  type LayoutBound,
  type LayoutConstraints,
  type LayoutConstraintsInput,
  type LayoutDirection,
  type LayoutEnvelope,
  type LayoutEnvelopeInput,
  type LayoutFact,
  type LayoutFitPolicy,
  type LayoutPreference,
  type LayoutPreferenceInput,
  type LayoutRenderInput,
  type LayoutRenderResult,
  type LogicalAlign,
  type LogicalAxis,
  type MeasureTextContentInput,
  type PlaceInRectInput,
  type ResolvedLayoutEnvelope,
  type StackLayoutChildInput,
  type StackLayoutInput,
  type StackLayoutResult,
  type StackTrack,
  type TextMeasurementAdapter,
  type TextMeasurementInput,
} from './core/layout/envelope.js';

// Mode rendering strategy
export {
  renderByMode,
  type ModeHandler,
  type ModeMap,
} from './core/mode-render.js';

export {
  BIJOU_BLOCK_ARTIFACT_VERSION,
  GRAPHQL_BIJOU_BLOCK_DEBUG_SUMMARY_VERSION,
  compileGraphqlBijouBlock,
  createGraphqlBijouBlockDebugSummary,
  lowerBijouBlockToUiScene,
  type BijouBlockArtifact,
  type BijouBlockArtifactVersion,
  type BijouBlockField,
  type BijouBlockFieldAction,
  type BijouBlockFieldBinding,
  type BijouBlockGroup,
  type CompileGraphqlBijouBlockOptions,
  type GraphqlBijouBlockDebugFieldFact,
  type GraphqlBijouBlockDebugGroupFact,
  type GraphqlBijouBlockDebugLowerModeFact,
  type GraphqlBijouBlockDebugSummary,
  type GraphqlBijouBlockDebugSummaryVersion,
} from './core/graphql-bijou-block.js';

export {
  UI_SCENE_IR_VERSION,
  UI_SCENE_RECEIPT_VERSION,
  createUiSceneTerminalReceipt,
  createUiSceneReceipt,
  hashUiSceneValue,
  lowerUiSceneToTerminalProof,
  lowerUiSceneToSurface,
  stableUiSceneStringify,
  validateUiSceneIr,
  type UiAction,
  type UiBinding,
  type UiCellSourceMapEntry,
  type UiI18nUse,
  type UiLayoutIntent,
  type UiNode,
  type UiNodeKind,
  type UiPortabilityClaim,
  type UiPortabilityLevel,
  type UiSceneIr,
  type UiSceneIrVersion,
  type UiSceneIssueCode,
  type UiSceneLowerMode,
  type UiSceneLoweringOptions,
  type UiSceneReceipt,
  type UiSceneReceiptVersion,
  type UiSceneSurfaceLowering,
  type UiSceneTerminalProof,
  type UiSceneValidationIssue,
  type UiSceneValidationResult,
  type UiSourceMapEntry,
  type UiStyleRef,
  type UiTargetProfile,
  type UiTextRef,
  type UiTokenUse,
} from './core/ui-scene-ir.js';
