import type { BijouContext, DagNode, TreeNode, TimelineEvent } from '@flyingrobots/bijou';
import {
  alert,
  box,
  headerBox,
  separator,
  skeleton,
  kbd,
  hyperlink,
  log,
  gradientText,
  progressBar,
  spinnerFrame,
  table,
  tree,
  accordion,
  timeline,
  tabs,
  breadcrumb,
  paginator,
  stepper,
  dag,
  enumeratedList,
  markdown,
} from '@flyingrobots/bijou';
import { SAMPLE_DAG, SAMPLE_TIMELINE, SAMPLE_TREE } from './registry-samples.js';

export const DATA: ComponentEntry[] = [
  {
    id: 'table',
    name: 'table()',
    subtitle: 'Data tables with columns',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# table()',
      '',
      'Tabular data display with typed columns, alignment, and width constraints.',
      '',
      '**Degradation:** Rich shows bordered table. Pipe shows TSV. Accessible shows row-label format.',
    ].join('\n'),
    render: (w, ctx) => table({
      columns: [
        { header: 'Name', width: Math.min(14, Math.floor(w / 4)) },
        { header: 'Role', width: Math.min(12, Math.floor(w / 4)) },
        { header: 'Status', width: Math.min(10, Math.floor(w / 4)) },
      ],
      rows: [
        ['Alice', 'Engineer', 'active'],
        ['Bob', 'Designer', 'away'],
        ['Carol', 'PM', 'offline'],
      ],
      ctx,
    }),
  },
  {
    id: 'tree',
    name: 'tree()',
    subtitle: 'Hierarchical tree views',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# tree()',
      '',
      'Indented tree display with unicode branch characters.',
      '',
      '**Degradation:** Rich shows styled tree lines. Pipe shows ASCII tree. Accessible shows indented list.',
    ].join('\n'),
    render: (_w, ctx) => tree(SAMPLE_TREE, { ctx }),
  },
  {
    id: 'accordion',
    name: 'accordion()',
    subtitle: 'Expandable content sections',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# accordion()',
      '',
      'Static expandable/collapsible content sections. For interactive accordion,',
      'see `interactiveAccordion()` in bijou-tui.',
      '',
      '**Degradation:** Rich shows styled headers. Pipe/accessible show text sections.',
    ].join('\n'),
    render: (_w, ctx) => accordion([
      { title: 'Getting Started', content: 'Install with npm install @flyingrobots/bijou', expanded: true },
      { title: 'Configuration', content: 'Set BIJOU_THEME env var to choose a preset.', expanded: false },
      { title: 'Advanced', content: 'Use createBijou() for custom port wiring.', expanded: false },
    ], { ctx }),
  },
  {
    id: 'timeline',
    name: 'timeline()',
    subtitle: 'Event timelines with status',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# timeline()',
      '',
      'Vertical timeline with status-colored markers.',
      'Statuses: `success`, `active`, `warning`, `muted`.',
      '',
      '**Degradation:** Rich shows colored dots + lines. Pipe shows `[STATUS] label`. Accessible same as pipe.',
    ].join('\n'),
    render: (_w, ctx) => timeline(SAMPLE_TIMELINE, { ctx }),
  },
  {
    id: 'tabs',
    name: 'tabs()',
    subtitle: 'Tab bar navigation',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# tabs()',
      '',
      'Static tab bar with active tab highlighting and optional badge counts.',
      '',
      '**Degradation:** Rich shows styled tabs. Pipe shows `[active] inactive`. Accessible shows labeled list.',
    ].join('\n'),
    render: (_w, ctx) => [
      tabs([
        { label: 'Overview', active: true },
        { label: 'Files', badge: '12' },
        { label: 'Settings' },
      ], { ctx }),
      '',
      tabs([
        { label: 'Home' },
        { label: 'Dashboard', active: true, badge: '3' },
        { label: 'Logs' },
      ], { ctx }),
    ].join('\n'),
  },
  {
    id: 'breadcrumb',
    name: 'breadcrumb()',
    subtitle: 'Navigation breadcrumb trails',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# breadcrumb()',
      '',
      'Horizontal navigation breadcrumb with separator characters.',
      '',
      '**Degradation:** Rich shows styled path. Pipe/accessible show slash-separated text.',
    ].join('\n'),
    render: (_w, ctx) => [
      breadcrumb(['Home', 'Projects', 'Bijou', 'src'], { ctx }),
      breadcrumb(['Settings', 'Theme', 'Colors'], { ctx }),
    ].join('\n'),
  },
  {
    id: 'paginator',
    name: 'paginator()',
    subtitle: 'Page indicators (dots and text)',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# paginator()',
      '',
      'Dot-style or text-style page indicators.',
      '',
      '**Degradation:** Rich shows styled dots. Pipe/accessible show `Page X of Y`.',
    ].join('\n'),
    render: (_w, ctx) => [
      paginator({ current: 0, total: 5, ctx }),
      paginator({ current: 2, total: 5, ctx }),
      paginator({ current: 4, total: 5, ctx }),
    ].join('\n'),
  },
  {
    id: 'stepper',
    name: 'stepper()',
    subtitle: 'Step progress indicators',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# stepper()',
      '',
      'Multi-step progress indicator showing completed, active, and pending steps.',
      '',
      '**Degradation:** Rich shows styled steps. Pipe/accessible show numbered step list.',
    ].join('\n'),
    render: (_w, ctx) => stepper([
      { label: 'Account', status: 'complete' },
      { label: 'Profile', status: 'active' },
      { label: 'Review', status: 'pending' },
      { label: 'Done', status: 'pending' },
    ], { ctx }),
  },
  {
    id: 'dag',
    name: 'dag()',
    subtitle: 'Directed acyclic graph',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# dag()',
      '',
      'ASCII art directed acyclic graph with status badges, edge routing,',
      'node selection, and highlight paths.',
      '',
      '**Degradation:** Rich shows colored graph. Pipe shows plain dependency lines. Accessible shows dependency list.',
    ].join('\n'),
    render: (w, ctx) => dag(SAMPLE_DAG, {
      selectedId: 'dev',
      highlightPath: ['plan', 'dev', 'test', 'ship'],
      maxWidth: Math.max(50, w),
      ctx,
    }),
  },
  {
    id: 'enumerated-list',
    name: 'enumeratedList()',
    subtitle: 'Ordered/unordered lists',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# enumeratedList()',
      '',
      'Numbered or bulleted lists with 6 bullet styles:',
      '`arabic`, `alpha`, `roman`, `bullet`, `dash`, `none`.',
      '',
      '**Degradation:** All modes render similarly (text-based).',
    ].join('\n'),
    render: (_w, ctx) => [
      enumeratedList(['First item', 'Second item', 'Third item'], { style: 'arabic', ctx }),
      '',
      enumeratedList(['Alpha one', 'Alpha two', 'Alpha three'], { style: 'alpha', ctx }),
      '',
      enumeratedList(['Bullet point', 'Another point'], { style: 'bullet', ctx }),
    ].join('\n'),
  },
  {
    id: 'markdown',
    name: 'markdown()',
    subtitle: 'Terminal markdown renderer',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# markdown()',
      '',
      'Renders markdown in the terminal with headings, bold/italic,',
      'code blocks, blockquotes, links, and lists.',
      '',
      '**Degradation:** Rich shows styled markdown. Pipe shows plain text. Accessible shows simplified text.',
    ].join('\n'),
    render: (w, ctx) => markdown([
      '## Hello World',
      '',
      'This is **bold** and *italic* text.',
      '',
      '> A blockquote with wisdom.',
      '',
      '```ts',
      'const x = 42;',
      '```',
      '',
      '- Item one',
      '- Item two',
    ].join('\n'), { width: Math.min(50, w), ctx }),
  },
];

// ---------------------------------------------------------------------------
// Form components (TIER 3 — static preview only)
// ---------------------------------------------------------------------------
