import {
  box,
} from '@flyingrobots/bijou';
import type { ComponentEntry } from './types.js';

export const FORMS: ComponentEntry[] = [
  {
    id: 'select',
    name: 'select()',
    subtitle: 'Single-select menu',
    pkg: 'bijou',
    tier: 3,
    description: [
      '# select()',
      '',
      'Interactive single-selection menu with keyboard navigation.',
      'Arrow keys move the cursor, Enter selects.',
      '',
      '**Interactive component** — cannot be embedded in this showcase.',
      'Run standalone to try it:',
      '',
      '```sh',
      'npx tsx examples/select/main.ts',
      '```',
    ].join('\n'),
    render: (w, ctx) => box([
      '  ? Pick a color',
      '',
      '  > Red       (highlighted)',
      '    Blue',
      '    Green',
      '    Yellow',
      '',
      '  (arrow keys navigate, enter selects)',
    ].join('\n'), { width: Math.min(40, w), ctx }),
  },
  {
    id: 'multiselect',
    name: 'multiselect()',
    subtitle: 'Checkbox multi-select',
    pkg: 'bijou',
    tier: 3,
    description: [
      '# multiselect()',
      '',
      'Interactive multi-selection with checkboxes. Space toggles,',
      'Enter confirms. Supports `maxVisible` scrolling.',
      '',
      '**Interactive component** — run standalone:',
      '',
      '```sh',
      'npx tsx examples/multiselect/main.ts',
      '```',
    ].join('\n'),
    render: (w, ctx) => box([
      '  ? Select toppings',
      '',
      '  [x] Cheese',
      '  [ ] Pepperoni',
      '  [x] Mushrooms',
      '  [ ] Olives',
      '',
      '  (space toggles, enter confirms)',
    ].join('\n'), { width: Math.min(40, w), ctx }),
  },
  {
    id: 'confirm',
    name: 'confirm()',
    subtitle: 'Yes/no confirmation',
    pkg: 'bijou',
    tier: 3,
    description: [
      '# confirm()',
      '',
      'Simple yes/no confirmation prompt with default value support.',
      '',
      '**Interactive component** — run standalone:',
      '',
      '```sh',
      'npx tsx examples/confirm/main.ts',
      '```',
    ].join('\n'),
    render: (w, ctx) => box([
      '  ? Continue with deployment? (Y/n)',
      '',
      '  (y/n or enter for default)',
    ].join('\n'), { width: Math.min(42, w), ctx }),
  },
  {
    id: 'input',
    name: 'input()',
    subtitle: 'Text input with validation',
    pkg: 'bijou',
    tier: 3,
    description: [
      '# input()',
      '',
      'Single-line text input with placeholder, validation, and required mode.',
      '',
      '**Interactive component** — run standalone:',
      '',
      '```sh',
      'npx tsx examples/input/main.ts',
      '```',
    ].join('\n'),
    render: (w, ctx) => box([
      '  ? Enter your name',
      '',
      '  > Alice_',
      '',
      '  (type and press enter)',
    ].join('\n'), { width: Math.min(40, w), ctx }),
  },
  {
    id: 'filter',
    name: 'filter()',
    subtitle: 'Fuzzy-filter select',
    pkg: 'bijou',
    tier: 3,
    description: [
      '# filter()',
      '',
      'Type-to-filter selection with fuzzy keyword matching.',
      'Supports vim-style normal/insert mode switching.',
      '',
      '**Interactive component** — run standalone:',
      '',
      '```sh',
      'npx tsx examples/filter/main.ts',
      '```',
    ].join('\n'),
    render: (w, ctx) => box([
      '  ? Search files',
      '  > src/comp_',
      '',
      '  > src/components/box.ts',
      '    src/components/badge.ts',
      '    src/components/alert.ts',
      '',
      '  3 matches',
    ].join('\n'), { width: Math.min(42, w), ctx }),
  },
  {
    id: 'textarea',
    name: 'textarea()',
    subtitle: 'Multi-line text input',
    pkg: 'bijou',
    tier: 3,
    description: [
      '# textarea()',
      '',
      'Multi-line text editor with cursor navigation, line numbers,',
      'and maxLength enforcement.',
      '',
      '**Interactive component** — run standalone:',
      '',
      '```sh',
      'npx tsx examples/textarea/main.ts',
      '```',
    ].join('\n'),
    render: (w, ctx) => box([
      '  ? Describe the issue',
      '',
      '  1 | The build fails when',
      '  2 | running on Node 22_',
      '  3 |',
      '',
      '  (ctrl+d to submit)',
    ].join('\n'), { width: Math.min(42, w), ctx }),
  },
  {
    id: 'wizard',
    name: 'wizard()',
    subtitle: 'Multi-step form orchestration',
    pkg: 'bijou',
    tier: 3,
    description: [
      '# wizard()',
      '',
      'Multi-step form with conditional skip logic, back navigation,',
      'and step progress display.',
      '',
      '**Interactive component** — run standalone:',
      '',
      '```sh',
      'npx tsx examples/wizard/main.ts',
      '```',
    ].join('\n'),
    render: (w, ctx) => box([
      '  Step 1 of 3: Account Setup',
      '',
      '  ? Enter username',
      '  > _',
      '',
      '  Next: Profile  |  Then: Review',
    ].join('\n'), { width: Math.min(42, w), ctx }),
  },
  {
    id: 'group',
    name: 'group()',
    subtitle: 'Multi-field form group',
    pkg: 'bijou',
    tier: 3,
    description: [
      '# group()',
      '',
      'Collects multiple form fields in sequence and returns all values.',
      '',
      '**Interactive component** — run standalone:',
      '',
      '```sh',
      'npx tsx examples/form-group/main.ts',
      '```',
    ].join('\n'),
    render: (w, ctx) => box([
      '  Form Group',
      '',
      '  name:    Alice',
      '  email:   alice@example.com',
      '  role:    Engineer',
      '',
      '  (fields collected sequentially)',
    ].join('\n'), { width: Math.min(42, w), ctx }),
  },
];

// ---------------------------------------------------------------------------
// TUI building blocks (TIER 2 — description + static preview)
// ---------------------------------------------------------------------------
