import type { BijouContext, DagNode, TreeNode, TimelineEvent } from '@flyingrobots/bijou';
import {
  alert,
  box,
  headerBox,
  separator,
  skeleton,
  kbd,
  hyperlink,
  log,
  gradientText,
  progressBar,
  spinnerFrame,
  table,
  tree,
  accordion,
  timeline,
  tabs,
  breadcrumb,
  paginator,
  stepper,
  dag,
  enumeratedList,
  markdown,
} from '@flyingrobots/bijou';
import { SAMPLE_DAG, SAMPLE_TIMELINE, SAMPLE_TREE } from './registry-samples.js';

export const DISPLAY: ComponentEntry[] = [
  {
    id: 'box',
    name: 'box() / headerBox()',
    subtitle: 'Bordered containers',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# box() / headerBox()',
      '',
      'Unicode box-drawing containers with optional titles, padding, width override,',
      'and background surface tokens. `headerBox()` adds a label + detail header.',
      '',
      '**Degradation:** Rich shows borders. Pipe returns content only. Accessible returns content only.',
    ].join('\n'),
    render: (w, ctx) => [
      box('A simple bordered box.', { width: Math.min(40, w), ctx }),
      '',
      headerBox('Deploy', { detail: 'v1.2.3 -> production', ctx }),
    ].join('\n'),
  },
  {
    id: 'alert',
    name: 'alert()',
    subtitle: 'Boxed alerts with icons',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# alert()',
      '',
      'Boxed notification alerts with status icons and variant coloring.',
      'Variants: `info`, `success`, `warning`, `error`.',
      '',
      '**Degradation:** Rich shows bordered box with icon. Pipe/accessible show text with prefix.',
    ].join('\n'),
    render: (w, ctx) => [
      alert('Deployment successful.', { variant: 'success', ctx }),
      '',
      alert('Check your configuration.', { variant: 'warning', ctx }),
      '',
      alert('Connection refused on port 5432.', { variant: 'error', ctx }),
    ].join('\n'),
  },
  {
    id: 'badge',
    name: 'badge()',
    subtitle: 'Inline status badges (7 variants)',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# badge()',
      '',
      'Compact inline status indicators. Inverse-colored pills.',
      'Variants: `success`, `error`, `warning`, `info`, `muted`, `accent`, `primary`.',
      '',
      '**Degradation:** Rich shows colored pill. Pipe shows plain text. Accessible shows `[TEXT]` brackets.',
    ].join('\n'),
    render: (_w, ctx) => column([
      row([
        badgeSurface('SUCCESS', 'success', ctx),
        '  ',
        badgeSurface('ERROR', 'error', ctx),
        '  ',
        badgeSurface('WARNING', 'warning', ctx),
      ]),
      row([
        badgeSurface('INFO', 'info', ctx),
        '  ',
        badgeSurface('MUTED', 'muted', ctx),
        '  ',
        badgeSurface('ACCENT', 'accent', ctx),
        '  ',
        badgeSurface('PRIMARY', 'primary', ctx),
      ]),
      spacer(1, 1),
      row([
        'Server is ',
        badgeSurface('RUNNING', 'success', ctx),
        ' on port ',
        badgeSurface('3000', 'primary', ctx),
      ]),
    ]),
  },
  {
    id: 'separator',
    name: 'separator()',
    subtitle: 'Horizontal dividers with labels',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# separator()',
      '',
      'Horizontal rule dividers with optional centered labels.',
      '',
      '**Degradation:** Rich shows styled line. Pipe shows dashes. Accessible shows dashes.',
    ].join('\n'),
    render: (w, ctx) => [
      separator({ width: Math.min(40, w), ctx }),
      '',
      separator({ label: 'Section Title', width: Math.min(40, w), ctx }),
      '',
      separator({ label: 'Another', width: Math.min(40, w), ctx }),
    ].join('\n'),
  },
  {
    id: 'skeleton',
    name: 'skeleton()',
    subtitle: 'Loading placeholders',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# skeleton()',
      '',
      'Animated shimmer-style loading placeholders for content that has not loaded yet.',
      '',
      '**Degradation:** Rich shows shaded blocks. Pipe/accessible show placeholder dashes.',
    ].join('\n'),
    render: (w, ctx) => [
      skeleton({ width: Math.min(30, w), height: 1, ctx }),
      skeleton({ width: Math.min(20, w), height: 1, ctx }),
      skeleton({ width: Math.min(25, w), height: 1, ctx }),
      '',
      skeleton({ width: Math.min(40, w), height: 3, ctx }),
    ].join('\n'),
  },
  {
    id: 'kbd',
    name: 'kbd()',
    subtitle: 'Keyboard shortcut display',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# kbd()',
      '',
      'Rendered keyboard shortcut badges, styled like physical key caps.',
      '',
      '**Degradation:** Rich shows styled key. Pipe/accessible show `[key]` brackets.',
    ].join('\n'),
    render: (_w, ctx) => [
      `${kbd('Ctrl', { ctx })}+${kbd('C', { ctx })} to quit`,
      `${kbd('Tab', { ctx })} to switch focus`,
      `${kbd('?', { ctx })} for help`,
      `${kbd('Esc', { ctx })} to cancel`,
    ].join('\n'),
  },
  {
    id: 'hyperlink',
    name: 'hyperlink()',
    subtitle: 'Clickable terminal links (OSC 8)',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# hyperlink()',
      '',
      'Clickable OSC 8 terminal hyperlinks. Falls back to `text (url)` in terminals',
      'that do not support the protocol.',
      '',
      '**Degradation:** Rich shows clickable link. Pipe/accessible show `text (url)`.',
    ].join('\n'),
    render: (_w, ctx) => [
      hyperlink('Bijou on GitHub', 'https://github.com/flyingrobots/bijou', { ctx }),
      hyperlink('Documentation', 'https://bijou.dev/docs', { ctx }),
    ].join('\n'),
  },
  {
    id: 'log',
    name: 'log()',
    subtitle: 'Leveled styled output',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# log()',
      '',
      'Leveled log output with status-colored prefixes.',
      'Levels: `debug`, `info`, `warn`, `error`, `fatal`.',
      '',
      '**Degradation:** Rich shows colored prefix. Pipe shows `[LEVEL]` prefix. Accessible same as pipe.',
    ].join('\n'),
    render: (_w, ctx) => [
      log('debug', 'Connecting to database...', { ctx }),
      log('info', 'Server started on port 3000', { ctx }),
      log('warn', 'Deprecated API used in /v1/users', { ctx }),
      log('error', 'Connection refused: ECONNREFUSED', { ctx }),
      log('fatal', 'Unrecoverable state — shutting down', { ctx }),
    ].join('\n'),
  },
  {
    id: 'gradient-text',
    name: 'gradientText()',
    subtitle: 'Gradient-colored text',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# gradientText()',
      '',
      'Apply RGB color gradients to text strings.',
      '',
      '**Degradation:** Rich shows gradient. Pipe/accessible return plain text.',
    ].join('\n'),
    render: (_w, ctx) => [
      gradientText('Hello, beautiful terminal!', { ctx }),
      gradientText('Bijou Component Library', { ctx }),
    ].join('\n'),
  },
  {
    id: 'progress-bar',
    name: 'progressBar()',
    subtitle: 'Static progress indicators',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# progressBar()',
      '',
      'Horizontal progress bar at a given percentage.',
      '',
      '**Degradation:** Rich shows colored bar. Pipe shows `[==>  ] 45%`. Accessible shows `Progress: 45%`.',
    ].join('\n'),
    render: (w, ctx) => {
      const barWidth = Math.min(36, w - 2);
      return [
        progressBar(25, { width: barWidth, ctx }),
        progressBar(50, { width: barWidth, ctx }),
        progressBar(75, { width: barWidth, ctx }),
        progressBar(100, { width: barWidth, ctx }),
      ].join('\n');
    },
  },
  {
    id: 'spinner',
    name: 'spinnerFrame()',
    subtitle: 'Animated spinner frames',
    pkg: 'bijou',
    tier: 1,
    description: [
      '# spinnerFrame()',
      '',
      'Returns a single frame of a spinner animation. Call with incrementing',
      'frame index from a `tick()` command for animation.',
      '',
      '**Degradation:** Rich shows animated glyph. Pipe/accessible show static text.',
    ].join('\n'),
    render: (_w, ctx) => [
      `Frame 0: ${spinnerFrame(0, { ctx })} Loading...`,
      `Frame 1: ${spinnerFrame(1, { ctx })} Loading...`,
      `Frame 2: ${spinnerFrame(2, { ctx })} Loading...`,
      `Frame 3: ${spinnerFrame(3, { ctx })} Loading...`,
    ].join('\n'),
  },
];

// ---------------------------------------------------------------------------
// Data components
// ---------------------------------------------------------------------------
