import {
  bindSchemaBlockInput,
  dividerBlock,
  dividerSchemaBlock,
  explainabilityWalkthroughBlock,
  explainabilityWalkthroughSchemaBlock,
  formattedDocumentBlock,
  formattedDocumentSchemaBlock,
  framedGroupBlock,
  framedGroupSchemaBlock,
  linkDestinationBlock,
  linkDestinationSchemaBlock,
  textEntryBlock,
  textEntrySchemaBlock,
} from '../../../packages/bijou/src/index.js';

const COMPONENT_FAMILY_SCHEMA_BLOCKS = [
  {
    block: framedGroupBlock,
    schemaBlock: framedGroupSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(framedGroupSchemaBlock, input),
    valid: {
      title: 'Release Checks',
      items: ['tests green', 'docs updated', 'PR linked'],
      selected: 'tests green',
      mode: 'review',
    },
    invalid: { title: 'Release Checks' },
    requiredFields: ['title', 'items'],
    optionalFields: ['selected', 'mode'],
    expectedSlots: {
      title: 'Release Checks',
      items: ['tests green', 'docs updated', 'PR linked'],
      selected: 'tests green',
      mode: 'review',
    },
  },
  {
    block: explainabilityWalkthroughBlock,
    schemaBlock: explainabilityWalkthroughSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(explainabilityWalkthroughSchemaBlock, input),
    valid: {
      title: 'Why this changed',
      steps: ['input changed', 'constraint tightened', 'preview re-rendered'],
      evidence: 'DF-040 playback',
      decision: 'keep grouped proof visible',
      nextStep: 'open lower-mode output',
    },
    invalid: { title: 'Why this changed' },
    requiredFields: ['title', 'steps'],
    optionalFields: ['evidence', 'decision', 'nextStep'],
    expectedSlots: {
      title: 'Why this changed',
      steps: ['input changed', 'constraint tightened', 'preview re-rendered'],
      evidence: 'DF-040 playback',
      decision: 'keep grouped proof visible',
      nextStep: 'open lower-mode output',
    },
  },
  {
    block: formattedDocumentBlock,
    schemaBlock: formattedDocumentSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(formattedDocumentSchemaBlock, input),
    valid: {
      heading: 'Blocks document',
      body: 'Use prose for persistent product truth.',
      callout: 'Lower modes keep the same heading and body facts.',
      code: 'block: FormattedDocumentBlock',
    },
    invalid: { heading: 'Blocks document' },
    requiredFields: ['heading', 'body'],
    optionalFields: ['callout', 'code'],
    expectedSlots: {
      heading: 'Blocks document',
      body: 'Use prose for persistent product truth.',
      callout: 'Lower modes keep the same heading and body facts.',
      code: 'block: FormattedDocumentBlock',
    },
  },
  {
    block: linkDestinationBlock,
    schemaBlock: linkDestinationSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(linkDestinationSchemaBlock, input),
    valid: {
      label: 'DOGFOOD.md',
      destination: 'docs/DOGFOOD.md',
      kind: 'docs',
      status: 'available',
    },
    invalid: { label: 'DOGFOOD.md' },
    requiredFields: ['label', 'destination'],
    optionalFields: ['kind', 'status'],
    expectedSlots: {
      label: 'DOGFOOD.md',
      destination: 'docs/DOGFOOD.md',
      kind: 'docs',
      status: 'available',
    },
  },
  {
    block: dividerBlock,
    schemaBlock: dividerSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(dividerSchemaBlock, input),
    valid: {
      label: 'Release Evidence',
      style: 'rule',
      density: 'compact',
    },
    invalid: { style: 'rule' },
    requiredFields: ['label'],
    optionalFields: ['style', 'density'],
    expectedSlots: {
      label: 'Release Evidence',
      style: 'rule',
      density: 'compact',
    },
  },
  {
    block: textEntryBlock,
    schemaBlock: textEntrySchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(textEntrySchemaBlock, input),
    valid: {
      field: 'Search docs',
      value: 'table',
      placeholder: 'type a query',
      validation: '4 results',
      results: 4,
    },
    invalid: { field: 'Search docs' },
    requiredFields: ['field', 'value'],
    optionalFields: ['placeholder', 'validation', 'results'],
    expectedSlots: {
      field: 'Search docs',
      value: 'table',
      placeholder: 'type a query',
      validation: '4 results',
      results: 4,
    },
  },
] as const;

export { COMPONENT_FAMILY_SCHEMA_BLOCKS };
