import { bindSchemaBlockInput, brandEmphasisBlock, brandEmphasisSchemaBlock, denseComparisonBlock, denseComparisonSchemaBlock, explorationListBlock, explorationListSchemaBlock, hierarchyBlock, hierarchySchemaBlock, modeAwarePrimitiveBlock, modeAwarePrimitiveSchemaBlock, temporalDependencyBlock, temporalDependencySchemaBlock } from '../../../packages/bijou/src/index.js';

const LATE_FAMILY_SCHEMA_BLOCKS = [
  {
    block: brandEmphasisBlock,
    schemaBlock: brandEmphasisSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(brandEmphasisSchemaBlock, input),
    valid: {
      brand: 'BIJOU',
      tagline: 'Terminal-native app blocks',
      decoration: 'accent rule',
      role: 'nonessential',
      selected: 'BIJOU',
    },
    invalid: { brand: 'BIJOU' },
    requiredFields: ['brand', 'tagline', 'decoration'],
    optionalFields: ['role', 'selected'],
    expectedSlots: {
      brand: 'BIJOU',
      tagline: 'Terminal-native app blocks',
      decoration: 'accent rule',
      role: 'nonessential',
      selected: 'BIJOU',
    },
  },
  {
    block: modeAwarePrimitiveBlock,
    schemaBlock: modeAwarePrimitiveSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(modeAwarePrimitiveSchemaBlock, input),
    valid: {
      primitive: 'metric badge',
      fact: 'latency-ms',
      value: 42,
      status: 'good',
      modeContract: 'visual and pipe',
      selected: 'metric badge',
    },
    invalid: { primitive: 'metric badge' },
    requiredFields: ['primitive', 'fact', 'value'],
    optionalFields: ['status', 'modeContract', 'selected'],
    expectedSlots: {
      primitive: 'metric badge',
      fact: 'latency-ms',
      value: 42,
      status: 'good',
      modeContract: 'visual and pipe',
      selected: 'metric badge',
    },
  },
  {
    block: denseComparisonBlock,
    schemaBlock: denseComparisonSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(denseComparisonSchemaBlock, input),
    valid: {
      title: 'Compare packages',
      metric: 'tests',
      left: '1820',
      right: '640',
      delta: '+12',
      selected: 'tests',
    },
    invalid: { title: 'Compare packages' },
    requiredFields: ['title', 'metric', 'left', 'right', 'delta'],
    optionalFields: ['selected'],
    expectedSlots: {
      title: 'Compare packages',
      metric: 'tests',
      left: '1820',
      right: '640',
      delta: '+12',
      selected: 'tests',
    },
  },
  {
    block: hierarchyBlock,
    schemaBlock: hierarchySchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(hierarchySchemaBlock, input),
    valid: {
      root: 'docs/',
      nodes: ['design/', 'DX-031.md', 'METHOD.md'],
      selected: 'design/',
      parent: 'docs/',
      depth: 1,
      expanded: 'true',
    },
    invalid: { root: 'docs/' },
    requiredFields: ['root', 'nodes', 'selected'],
    optionalFields: ['parent', 'depth', 'expanded'],
    expectedSlots: {
      root: 'docs/',
      nodes: ['design/', 'DX-031.md', 'METHOD.md'],
      selected: 'design/',
      parent: 'docs/',
      depth: 1,
      expanded: 'true',
    },
  },
  {
    block: explorationListBlock,
    schemaBlock: explorationListSchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(explorationListSchemaBlock, input),
    valid: {
      title: 'Explore components',
      facet: 'input',
      items: ['TextEntry field input', 'SingleChoice radio/select'],
      selected: 'TextEntry',
      preview: 'field input',
    },
    invalid: { title: 'Explore components' },
    requiredFields: ['title', 'facet', 'items', 'selected'],
    optionalFields: ['preview'],
    expectedSlots: {
      title: 'Explore components',
      facet: 'input',
      items: ['TextEntry field input', 'SingleChoice radio/select'],
      selected: 'TextEntry',
      preview: 'field input',
    },
  },
  {
    block: temporalDependencyBlock,
    schemaBlock: temporalDependencySchemaBlock,
    bind: (input: unknown) => bindSchemaBlockInput(temporalDependencySchemaBlock, input),
    valid: {
      title: 'Timeline',
      events: ['09:00 build', '09:05 test', '09:10 publish'],
      dependency: 'publish waits for test',
      selected: 'publish',
      dependsOn: 'test',
    },
    invalid: { title: 'Timeline' },
    requiredFields: ['title', 'events', 'dependency'],
    optionalFields: ['selected', 'dependsOn'],
    expectedSlots: {
      title: 'Timeline',
      events: ['09:00 build', '09:05 test', '09:10 publish'],
      dependency: 'publish waits for test',
      selected: 'publish',
      dependsOn: 'test',
    },
  },
] as const;

export { LATE_FAMILY_SCHEMA_BLOCKS };
