export const TRANCHE_A_CLEARED_PATHS = [
  'bench/src/cli.ts',
  'examples/docs/release-title.ts',
  'packages/bijou-i18n-tools/src/string-table.ts',
  'packages/bijou-i18n-tools/src/tools.ts',
  'packages/bijou-i18n/src/localization.ts',
  'packages/bijou-node/src/worker/worker.ts',
  'packages/bijou-tui/src/animate.ts',
  'packages/bijou-tui/src/app-frame-layers.ts',
  'packages/bijou-tui/src/app-frame-palette.ts',
  'packages/bijou-tui/src/input-map.ts',
  'packages/bijou-tui/src/pager.ts',
  'packages/bijou-tui/src/pipeline/middleware/surface-shaders.ts',
  'packages/bijou-tui/src/surface-diff.ts',
  'packages/bijou/src/core/block-tree-render.ts',
  'packages/bijou/src/core/components/dag-edges.ts',
  'packages/bijou/src/core/components/progress.ts',
  'packages/bijou/src/core/components/timer.ts',
  'packages/bijou/src/core/layout/geometry.ts',
  'packages/bijou/src/core/mode-lowering.ts',
  'packages/bijou/src/core/text/grapheme.ts',
  'packages/bijou/src/core/theme/dtcg.ts',
  'scripts/dogfood-i18n-completeness.ts',
  'scripts/release-readiness.ts',
  'scripts/smoke-dogfood-lib.ts',
  'scripts/workflow-shell-preflight.ts',
] as const;
